// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v3.21.12
// source: types.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "shared";

export interface Point2d {
  x: number;
  y: number;
}

export interface Star {
  pos: Point2d | undefined;
  z: number;
}

export interface Galaxy {
  stars: Star[];
}

function createBasePoint2d(): Point2d {
  return { x: 0, y: 0 };
}

export const Point2d: MessageFns<Point2d> = {
  encode(message: Point2d, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== 0) {
      writer.uint32(8).int32(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(16).int32(message.y);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Point2d {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePoint2d();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.x = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.y = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Point2d {
    return {
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
    };
  },

  toJSON(message: Point2d): unknown {
    const obj: any = {};
    if (message.x !== 0) {
      obj.x = Math.round(message.x);
    }
    if (message.y !== 0) {
      obj.y = Math.round(message.y);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Point2d>, I>>(base?: I): Point2d {
    return Point2d.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Point2d>, I>>(object: I): Point2d {
    const message = createBasePoint2d();
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    return message;
  },
};

function createBaseStar(): Star {
  return { pos: undefined, z: 0 };
}

export const Star: MessageFns<Star> = {
  encode(message: Star, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pos !== undefined) {
      Point2d.encode(message.pos, writer.uint32(10).fork()).join();
    }
    if (message.z !== 0) {
      writer.uint32(16).int32(message.z);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Star {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStar();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pos = Point2d.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.z = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Star {
    return {
      pos: isSet(object.pos) ? Point2d.fromJSON(object.pos) : undefined,
      z: isSet(object.z) ? globalThis.Number(object.z) : 0,
    };
  },

  toJSON(message: Star): unknown {
    const obj: any = {};
    if (message.pos !== undefined) {
      obj.pos = Point2d.toJSON(message.pos);
    }
    if (message.z !== 0) {
      obj.z = Math.round(message.z);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Star>, I>>(base?: I): Star {
    return Star.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Star>, I>>(object: I): Star {
    const message = createBaseStar();
    message.pos = (object.pos !== undefined && object.pos !== null) ? Point2d.fromPartial(object.pos) : undefined;
    message.z = object.z ?? 0;
    return message;
  },
};

function createBaseGalaxy(): Galaxy {
  return { stars: [] };
}

export const Galaxy: MessageFns<Galaxy> = {
  encode(message: Galaxy, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.stars) {
      Star.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Galaxy {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGalaxy();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stars.push(Star.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Galaxy {
    return { stars: globalThis.Array.isArray(object?.stars) ? object.stars.map((e: any) => Star.fromJSON(e)) : [] };
  },

  toJSON(message: Galaxy): unknown {
    const obj: any = {};
    if (message.stars?.length) {
      obj.stars = message.stars.map((e) => Star.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Galaxy>, I>>(base?: I): Galaxy {
    return Galaxy.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Galaxy>, I>>(object: I): Galaxy {
    const message = createBaseGalaxy();
    message.stars = object.stars?.map((e) => Star.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
